import Head from 'next/head'
import Image from 'next/image'
import { Oswald} from '@next/font/google'
import data from '../data/employees.json'
import Link from 'next/link'
import { useState } from 'react'
import Card from '@/components/Card/about'
import styles from '@/styles/About.module.css'

const oswald = Oswald({ subsets: ['latin'] })

export default function About() {
    const [information, setInformation] = useState([...data])

    return (
        <>
            <Head>
                <title>About Us</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <div class="nav-bar">
                    <div class="nav-name">Neo Culture Technology</div>
                    <div class="nav-btn">
                        <Link className={styles.link} href="..">Home</Link>
                    </div>
                </div>
                {
                    information && information.map((info, index) => {
                        return (
                            <Card 
                                class="employee-card"
                                key={index} 
                                firstName={info.firstName} 
                                lastName={info.lastName}
                                position={info.position}
                                age={info.age} 
                                colourCard="#6f8111"
                                colourInfo="#171717"
                                colourBorder="#ffffff"
                                font="17px"
                                fontColour="#ffffff"
                            />
                        )
                    })
                }
            </main>
        </>
    )
}
