const inter = Inter({ subsets: ['latin'] })

import Head from 'next/head'


export default function About() {
    return(
        <>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        {
          information && information.map((info, index) => {
            if (info.department.toLowerCase() === "doctor") {
            return(
              <Card key={index} degree={info.degree} colour="blue" font="50px" />
            )
          }
          })
        }

{
          information && information.map((info, index) => {
            if (info.department.toLowerCase() === "chemistry teacher") {
            return(
              <Card key={index} degree={info.degree} colour="blue" font="50px" />
            )
          }
          })
        }
  
  {
          information && information.map((info, index) => {
            if (info.department.toLowerCase() === "CEO") {
            return(
              <Card key={index} degree={info.degree} colour="yellow" font="50px" />
            )
          }
          })
        }
      </main>
        </>
    )
}