
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import data from '../data/employees.json'
import Link from 'next/link'
import { useState } from 'react'
import Card from '@/components/Card/about'
import styles from '@/styles/about.module.css'

export default function About() {
    return(
        <>
        <Head>
        <title>about Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        {
          information && information.map((info, index) => {
            if (info.department.toLowerCase() === "CEO") {
            return(
              <Card 
              key={index}
              firstName={info.firstName}
              lastName={info.lastName}
              occupation={info.occupation}
              graduated={info.graduated}
              colour="yellow" 
              font="50px" />
            )
          }
          })
        }
      </main>
        </>
    )
}